//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    
    public partial class getAssignedStudentsPerBatch_Result
    {
        public string FullName { get; set; }
        public string LocationName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string StudentCode { get; set; }
        public Nullable<int> BatchCode { get; set; }
        public Nullable<bool> isMappingActive { get; set; }
    }
}
