//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFA_Percentage_Result
    {
        public int Id { get; set; }
        public string KeyCode { get; set; }
        public string AdGroupCode { get; set; }
        public string CampaignCode { get; set; }
        public string Parent { get; set; }
        public Nullable<decimal> KeyNamePercentCount { get; set; }
        public Nullable<decimal> HeadlinePercentCount { get; set; }
        public Nullable<decimal> Descline1PercentCount { get; set; }
        public Nullable<decimal> Descline2PercentCount { get; set; }
        public Nullable<decimal> DispUrlPercentCount { get; set; }
        public Nullable<decimal> AdGroupNamePercentCount { get; set; }
    }
}
