//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignMaster
    {
        public int CampaignCode { get; set; }
        public Nullable<int> BatchCode { get; set; }
        public string CampaignName { get; set; }
        public string NetWorkType { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public int AccCode { get; set; }
        public string CreatedBy { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> RfaNo { get; set; }
        public int UserRfaNumber { get; set; }
    }
}
