//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class keywordmaster07JAN2018
    {
        public int KeyCode { get; set; }
        public string KeyName { get; set; }
        public string AvgMonthlySrch { get; set; }
        public string Competition { get; set; }
        public Nullable<decimal> SuggestedBid { get; set; }
        public Nullable<decimal> CTR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> FromMaster { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
