//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public long OrderID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PlanName { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string USERID { get; set; }
        public string tracking_id { get; set; }
        public string bank_ref_no { get; set; }
        public string order_status { get; set; }
        public string failure_message { get; set; }
        public string payment_mode { get; set; }
        public string card_name { get; set; }
        public string status_code { get; set; }
        public string status_message { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PlanCode { get; set; }
    }
}
