//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempKeywordMapping
    {
        public int id { get; set; }
        public Nullable<int> RowNo { get; set; }
        public string CampaignName { get; set; }
        public string AdgroupName { get; set; }
        public string KeywordName { get; set; }
        public string Bid { get; set; }
        public Nullable<long> BatchCode { get; set; }
        public Nullable<long> AccCode { get; set; }
        public string UserID { get; set; }
    }
}
