//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeHistory
    {
        public int ID { get; set; }
        public string ActivityName { get; set; }
        public string ActivitySummary { get; set; }
        public string ActivityDescription { get; set; }
        public string User { get; set; }
        public string ActivityDate { get; set; }
    }
}
