//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyWordRank
    {
        public int Id { get; set; }
        public Nullable<decimal> Heading { get; set; }
        public Nullable<decimal> DisplayUrl { get; set; }
        public Nullable<decimal> description1 { get; set; }
        public Nullable<decimal> description2 { get; set; }
        public Nullable<decimal> AdgroupName { get; set; }
    }
}
