//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAd
    {
        public int AdGroupCode { get; set; }
        public int ADCode { get; set; }
        public string ADText { get; set; }
        public string HeadLine { get; set; }
        public string DescLine1 { get; set; }
        public string DescLine2 { get; set; }
        public string DispUrl { get; set; }
        public string FinalUrl { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
