//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whisker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WhiskersDBEntities : DbContext
    {
        public WhiskersDBEntities()
            : base("name=WhiskersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BatchAndStudentMapping> BatchAndStudentMappings { get; set; }
        public DbSet<ChangeHistory> ChangeHistories { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<keyWordRank> keyWordRanks { get; set; }
        public DbSet<LocationMaster> LocationMasters { get; set; }
        public DbSet<MapKeywordsAG> MapKeywordsAGs { get; set; }
        public DbSet<RFA_Percentage_Result> RFA_Percentage_Result { get; set; }
        public DbSet<RFA_Result> RFA_Result { get; set; }
        public DbSet<RFAHistory> RFAHistories { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<AccountsMaster> AccountsMasters { get; set; }
        public DbSet<AdGroup> AdGroups { get; set; }
        public DbSet<BatchAndTrainerMapping> BatchAndTrainerMappings { get; set; }
        public DbSet<BatchMaster> BatchMasters { get; set; }
        public DbSet<CampaignMaster> CampaignMasters { get; set; }
        public DbSet<KeywordMaster> KeywordMasters { get; set; }
        public DbSet<RFAMaster> RFAMasters { get; set; }
        public DbSet<SearchQueryMaster> SearchQueryMasters { get; set; }
        public DbSet<tblAd> tblAds { get; set; }
        public DbSet<TempKeywordMapping> TempKeywordMappings { get; set; }
    
        public virtual int CancelAuction(string rfaId, string batchCode, string accCode)
        {
            var rfaIdParameter = rfaId != null ?
                new ObjectParameter("rfaId", rfaId) :
                new ObjectParameter("rfaId", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CancelAuction", rfaIdParameter, batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<CheckRFAStatus_Result> CheckRFAStatus(string accCode, string createdBy)
        {
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckRFAStatus_Result>("CheckRFAStatus", accCodeParameter, createdByParameter);
        }
    
        public virtual ObjectResult<GetAccountAdGrpReport_Result> GetAccountAdGrpReport(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAccountAdGrpReport_Result>("GetAccountAdGrpReport", batchCodeParameter);
        }
    
        public virtual ObjectResult<GetAccountCampReport_Result> GetAccountCampReport(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAccountCampReport_Result>("GetAccountCampReport", batchCodeParameter);
        }
    
        public virtual ObjectResult<GetAccountReport_Result> GetAccountReport(Nullable<int> batchCode, Nullable<int> accCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            var accCodeParameter = accCode.HasValue ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAccountReport_Result>("GetAccountReport", batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<getADGroupsOnDemand_Result> getADGroupsOnDemand(string batchCode, string accCode, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getADGroupsOnDemand_Result>("getADGroupsOnDemand", batchCodeParameter, accCodeParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getADGroupsOnDemand_03_Aug_2016_Result> getADGroupsOnDemand_03_Aug_2016(string batchCode, string accCode, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getADGroupsOnDemand_03_Aug_2016_Result>("getADGroupsOnDemand_03_Aug_2016", batchCodeParameter, accCodeParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getADGroupsOnDemand_23_07_16_Result> getADGroupsOnDemand_23_07_16(string batchCode, string accCode, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getADGroupsOnDemand_23_07_16_Result>("getADGroupsOnDemand_23_07_16", batchCodeParameter, accCodeParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getADGroupsOnDemand_23_07_16_2_Result> getADGroupsOnDemand_23_07_16_2(string batchCode, string accCode, string createdBy, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getADGroupsOnDemand_23_07_16_2_Result>("getADGroupsOnDemand_23_07_16_2", batchCodeParameter, accCodeParameter, createdByParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getAssignedStudentsPerBatch_Result> getAssignedStudentsPerBatch(string batchCode, string type)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAssignedStudentsPerBatch_Result>("getAssignedStudentsPerBatch", batchCodeParameter, typeParameter);
        }
    
        public virtual ObjectResult<GetBatchesOfTrainer_Result> GetBatchesOfTrainer(string trainerCode)
        {
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBatchesOfTrainer_Result>("GetBatchesOfTrainer", trainerCodeParameter);
        }
    
        public virtual ObjectResult<getCampaignAdsOnDemand_Result> getCampaignAdsOnDemand(string batchCode, string accCode, string userid, string campaignCode, string adGroupCode, string adCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            var adCodeParameter = adCode != null ?
                new ObjectParameter("AdCode", adCode) :
                new ObjectParameter("AdCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCampaignAdsOnDemand_Result>("getCampaignAdsOnDemand", batchCodeParameter, accCodeParameter, useridParameter, campaignCodeParameter, adGroupCodeParameter, adCodeParameter);
        }
    
        public virtual ObjectResult<getCampaignAdsOnDemand_24_07_16_Result> getCampaignAdsOnDemand_24_07_16(string batchCode, string accCode, string userid, string campaignCode, string adGroupCode, string adCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            var adCodeParameter = adCode != null ?
                new ObjectParameter("AdCode", adCode) :
                new ObjectParameter("AdCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCampaignAdsOnDemand_24_07_16_Result>("getCampaignAdsOnDemand_24_07_16", batchCodeParameter, accCodeParameter, useridParameter, campaignCodeParameter, adGroupCodeParameter, adCodeParameter);
        }
    
        public virtual ObjectResult<GetCampaignMatrix_Report_Result> GetCampaignMatrix_Report(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCampaignMatrix_Report_Result>("GetCampaignMatrix_Report", batchCodeParameter);
        }
    
        public virtual ObjectResult<getChangeHistoryOnDemand_Result> getChangeHistoryOnDemand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getChangeHistoryOnDemand_Result>("getChangeHistoryOnDemand");
        }
    
        public virtual ObjectResult<getErrorBaordOnDemand_Result> getErrorBaordOnDemand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getErrorBaordOnDemand_Result>("getErrorBaordOnDemand");
        }
    
        public virtual ObjectResult<GetIndustryReport_TopKey_Result> GetIndustryReport_TopKey(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIndustryReport_TopKey_Result>("GetIndustryReport_TopKey", batchCodeParameter);
        }
    
        public virtual ObjectResult<GetIndustryReport_TopKeybak16SEP2016_Result> GetIndustryReport_TopKeybak16SEP2016(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIndustryReport_TopKeybak16SEP2016_Result>("GetIndustryReport_TopKeybak16SEP2016", batchCodeParameter);
        }
    
        public virtual ObjectResult<getKeywordPlannerImportCount_Result> getKeywordPlannerImportCount(string batchCode, string accCode, Nullable<int> status)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getKeywordPlannerImportCount_Result>("getKeywordPlannerImportCount", batchCodeParameter, accCodeParameter, statusParameter);
        }
    
        public virtual ObjectResult<getMappedkeyWordsOnDemand_Result> getMappedkeyWordsOnDemand(string batchCode, string accCode, string createdBy, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMappedkeyWordsOnDemand_Result>("getMappedkeyWordsOnDemand", batchCodeParameter, accCodeParameter, createdByParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getMappedkeyWordsOnDemand_02_aug_2016_Result> getMappedkeyWordsOnDemand_02_aug_2016(string batchCode, string accCode, string createdBy, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMappedkeyWordsOnDemand_02_aug_2016_Result>("getMappedkeyWordsOnDemand_02_aug_2016", batchCodeParameter, accCodeParameter, createdByParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getMappedkeyWordsOnDemand_02_aug_2016_15_25_Result> getMappedkeyWordsOnDemand_02_aug_2016_15_25(string batchCode, string accCode, string createdBy, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMappedkeyWordsOnDemand_02_aug_2016_15_25_Result>("getMappedkeyWordsOnDemand_02_aug_2016_15_25", batchCodeParameter, accCodeParameter, createdByParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getMappedkeyWordsOnDemand_22_07_16_Result> getMappedkeyWordsOnDemand_22_07_16(string batchCode, string accCode, string createdBy, string campaignCode, string adGroupCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMappedkeyWordsOnDemand_22_07_16_Result>("getMappedkeyWordsOnDemand_22_07_16", batchCodeParameter, accCodeParameter, createdByParameter, campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<getSingleKeywordDetails_Result> getSingleKeywordDetails(string adGroupCode)
        {
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSingleKeywordDetails_Result>("getSingleKeywordDetails", adGroupCodeParameter);
        }
    
        public virtual ObjectResult<GetTop5_Themes_Result> GetTop5_Themes(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTop5_Themes_Result>("GetTop5_Themes", batchCodeParameter);
        }
    
        public virtual ObjectResult<GetTopAccounts_Result> GetTopAccounts(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopAccounts_Result>("GetTopAccounts", batchCodeParameter);
        }
    
        public virtual ObjectResult<getTrainerToBatch_Result> getTrainerToBatch(string patternValue, string batchCode)
        {
            var patternValueParameter = patternValue != null ?
                new ObjectParameter("patternValue", patternValue) :
                new ObjectParameter("patternValue", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTrainerToBatch_Result>("getTrainerToBatch", patternValueParameter, batchCodeParameter);
        }
    
        public virtual ObjectResult<prcAccountsPerBatches_Result> prcAccountsPerBatches(string batchCode, string accCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcAccountsPerBatches_Result>("prcAccountsPerBatches", batchCodeParameter, accCodeParameter);
        }
    
        public virtual int prcAssignedStudentsAndTrainer(string batchCode, string userID, string assignedTo, string isMappingActive, string status)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var assignedToParameter = assignedTo != null ?
                new ObjectParameter("AssignedTo", assignedTo) :
                new ObjectParameter("AssignedTo", typeof(string));
    
            var isMappingActiveParameter = isMappingActive != null ?
                new ObjectParameter("isMappingActive", isMappingActive) :
                new ObjectParameter("isMappingActive", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcAssignedStudentsAndTrainer", batchCodeParameter, userIDParameter, assignedToParameter, isMappingActiveParameter, statusParameter);
        }
    
        public virtual ObjectResult<prcBatchesOnDemand_Result> prcBatchesOnDemand(Nullable<int> batchTime, string trainerCode, string locationCode, string batchCode)
        {
            var batchTimeParameter = batchTime.HasValue ?
                new ObjectParameter("BatchTime", batchTime) :
                new ObjectParameter("BatchTime", typeof(int));
    
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            var locationCodeParameter = locationCode != null ?
                new ObjectParameter("LocationCode", locationCode) :
                new ObjectParameter("LocationCode", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcBatchesOnDemand_Result>("prcBatchesOnDemand", batchTimeParameter, trainerCodeParameter, locationCodeParameter, batchCodeParameter);
        }
    
        public virtual int prcChangeHistory(string activityName, string activitySummary, string activityDescription, string user)
        {
            var activityNameParameter = activityName != null ?
                new ObjectParameter("ActivityName", activityName) :
                new ObjectParameter("ActivityName", typeof(string));
    
            var activitySummaryParameter = activitySummary != null ?
                new ObjectParameter("ActivitySummary", activitySummary) :
                new ObjectParameter("ActivitySummary", typeof(string));
    
            var activityDescriptionParameter = activityDescription != null ?
                new ObjectParameter("ActivityDescription", activityDescription) :
                new ObjectParameter("ActivityDescription", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcChangeHistory", activityNameParameter, activitySummaryParameter, activityDescriptionParameter, userParameter);
        }
    
        public virtual ObjectResult<prcCheckKeywordFromMapKeywordsAG_Result> prcCheckKeywordFromMapKeywordsAG(Nullable<int> keywordCode, string adGroupCode)
        {
            var keywordCodeParameter = keywordCode.HasValue ?
                new ObjectParameter("KeywordCode", keywordCode) :
                new ObjectParameter("KeywordCode", typeof(int));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcCheckKeywordFromMapKeywordsAG_Result>("prcCheckKeywordFromMapKeywordsAG", keywordCodeParameter, adGroupCodeParameter);
        }
    
        public virtual int prcCreateAccount(string accName, string imagePath, string description, string inputAccountCode, string status)
        {
            var accNameParameter = accName != null ?
                new ObjectParameter("AccName", accName) :
                new ObjectParameter("AccName", typeof(string));
    
            var imagePathParameter = imagePath != null ?
                new ObjectParameter("ImagePath", imagePath) :
                new ObjectParameter("ImagePath", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var inputAccountCodeParameter = inputAccountCode != null ?
                new ObjectParameter("InputAccountCode", inputAccountCode) :
                new ObjectParameter("InputAccountCode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateAccount", accNameParameter, imagePathParameter, descriptionParameter, inputAccountCodeParameter, statusParameter);
        }
    
        public virtual int prcCreateAD(string adGroupCode, string headLine, string descLine1, string descLine2, string dispUrl, string finalUrl, string createdBy, string adCode)
        {
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            var headLineParameter = headLine != null ?
                new ObjectParameter("HeadLine", headLine) :
                new ObjectParameter("HeadLine", typeof(string));
    
            var descLine1Parameter = descLine1 != null ?
                new ObjectParameter("DescLine1", descLine1) :
                new ObjectParameter("DescLine1", typeof(string));
    
            var descLine2Parameter = descLine2 != null ?
                new ObjectParameter("DescLine2", descLine2) :
                new ObjectParameter("DescLine2", typeof(string));
    
            var dispUrlParameter = dispUrl != null ?
                new ObjectParameter("DispUrl", dispUrl) :
                new ObjectParameter("DispUrl", typeof(string));
    
            var finalUrlParameter = finalUrl != null ?
                new ObjectParameter("FinalUrl", finalUrl) :
                new ObjectParameter("FinalUrl", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var adCodeParameter = adCode != null ?
                new ObjectParameter("AdCode", adCode) :
                new ObjectParameter("AdCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateAD", adGroupCodeParameter, headLineParameter, descLine1Parameter, descLine2Parameter, dispUrlParameter, finalUrlParameter, createdByParameter, adCodeParameter);
        }
    
        public virtual int prcCreateADGroup(string campaignCode, string adGroupName, string accCode, string headLine, string descLine1, string descLine2, string dispUrl, string finalUrl, string createdBy, string adGroupCode)
        {
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupNameParameter = adGroupName != null ?
                new ObjectParameter("AdGroupName", adGroupName) :
                new ObjectParameter("AdGroupName", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var headLineParameter = headLine != null ?
                new ObjectParameter("HeadLine", headLine) :
                new ObjectParameter("HeadLine", typeof(string));
    
            var descLine1Parameter = descLine1 != null ?
                new ObjectParameter("DescLine1", descLine1) :
                new ObjectParameter("DescLine1", typeof(string));
    
            var descLine2Parameter = descLine2 != null ?
                new ObjectParameter("DescLine2", descLine2) :
                new ObjectParameter("DescLine2", typeof(string));
    
            var dispUrlParameter = dispUrl != null ?
                new ObjectParameter("DispUrl", dispUrl) :
                new ObjectParameter("DispUrl", typeof(string));
    
            var finalUrlParameter = finalUrl != null ?
                new ObjectParameter("FinalUrl", finalUrl) :
                new ObjectParameter("FinalUrl", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateADGroup", campaignCodeParameter, adGroupNameParameter, accCodeParameter, headLineParameter, descLine1Parameter, descLine2Parameter, dispUrlParameter, finalUrlParameter, createdByParameter, adGroupCodeParameter);
        }
    
        public virtual int prcCreateBatch(string batchName, string location, string address, Nullable<System.DateTime> stratDate, Nullable<System.DateTime> endDate, string inputLocationCode, Nullable<System.TimeSpan> time, string inputBatchCode, string status)
        {
            var batchNameParameter = batchName != null ?
                new ObjectParameter("BatchName", batchName) :
                new ObjectParameter("BatchName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var stratDateParameter = stratDate.HasValue ?
                new ObjectParameter("StratDate", stratDate) :
                new ObjectParameter("StratDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var inputLocationCodeParameter = inputLocationCode != null ?
                new ObjectParameter("InputLocationCode", inputLocationCode) :
                new ObjectParameter("InputLocationCode", typeof(string));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("Time", time) :
                new ObjectParameter("Time", typeof(System.TimeSpan));
    
            var inputBatchCodeParameter = inputBatchCode != null ?
                new ObjectParameter("InputBatchCode", inputBatchCode) :
                new ObjectParameter("InputBatchCode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateBatch", batchNameParameter, locationParameter, addressParameter, stratDateParameter, endDateParameter, inputLocationCodeParameter, timeParameter, inputBatchCodeParameter, statusParameter);
        }
    
        public virtual int prcCreateCampaign(string campaignName, Nullable<int> campaignCode, Nullable<int> networdType, string location, Nullable<decimal> budget, Nullable<int> accCode, string createdBy, string batchCode, Nullable<bool> isActive)
        {
            var campaignNameParameter = campaignName != null ?
                new ObjectParameter("CampaignName", campaignName) :
                new ObjectParameter("CampaignName", typeof(string));
    
            var campaignCodeParameter = campaignCode.HasValue ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(int));
    
            var networdTypeParameter = networdType.HasValue ?
                new ObjectParameter("NetwordType", networdType) :
                new ObjectParameter("NetwordType", typeof(int));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var budgetParameter = budget.HasValue ?
                new ObjectParameter("Budget", budget) :
                new ObjectParameter("Budget", typeof(decimal));
    
            var accCodeParameter = accCode.HasValue ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateCampaign", campaignNameParameter, campaignCodeParameter, networdTypeParameter, locationParameter, budgetParameter, accCodeParameter, createdByParameter, batchCodeParameter, isActiveParameter);
        }
    
        public virtual int prcCreateErrLog(string userId, string controller, string action, string exception, string stacktrace, Nullable<bool> errStatus)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var controllerParameter = controller != null ?
                new ObjectParameter("Controller", controller) :
                new ObjectParameter("Controller", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var exceptionParameter = exception != null ?
                new ObjectParameter("Exception", exception) :
                new ObjectParameter("Exception", typeof(string));
    
            var stacktraceParameter = stacktrace != null ?
                new ObjectParameter("Stacktrace", stacktrace) :
                new ObjectParameter("Stacktrace", typeof(string));
    
            var errStatusParameter = errStatus.HasValue ?
                new ObjectParameter("ErrStatus", errStatus) :
                new ObjectParameter("ErrStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateErrLog", userIdParameter, controllerParameter, actionParameter, exceptionParameter, stacktraceParameter, errStatusParameter);
        }
    
        public virtual int prcCreateKeyword(string keywordName, string keywordAvgMonthSearch, string keywordSuggestBid, string keywordSuggestCTR, string inputKeywordCode, string status)
        {
            var keywordNameParameter = keywordName != null ?
                new ObjectParameter("KeywordName", keywordName) :
                new ObjectParameter("KeywordName", typeof(string));
    
            var keywordAvgMonthSearchParameter = keywordAvgMonthSearch != null ?
                new ObjectParameter("KeywordAvgMonthSearch", keywordAvgMonthSearch) :
                new ObjectParameter("KeywordAvgMonthSearch", typeof(string));
    
            var keywordSuggestBidParameter = keywordSuggestBid != null ?
                new ObjectParameter("KeywordSuggestBid", keywordSuggestBid) :
                new ObjectParameter("KeywordSuggestBid", typeof(string));
    
            var keywordSuggestCTRParameter = keywordSuggestCTR != null ?
                new ObjectParameter("KeywordSuggestCTR", keywordSuggestCTR) :
                new ObjectParameter("KeywordSuggestCTR", typeof(string));
    
            var inputKeywordCodeParameter = inputKeywordCode != null ?
                new ObjectParameter("InputKeywordCode", inputKeywordCode) :
                new ObjectParameter("InputKeywordCode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateKeyword", keywordNameParameter, keywordAvgMonthSearchParameter, keywordSuggestBidParameter, keywordSuggestCTRParameter, inputKeywordCodeParameter, statusParameter);
        }
    
        public virtual int prcCreateMappedKeywords(string keywordName, string keywordCode, string adGroupCode, string keywordBid, string createdBy, Nullable<int> flag)
        {
            var keywordNameParameter = keywordName != null ?
                new ObjectParameter("KeywordName", keywordName) :
                new ObjectParameter("KeywordName", typeof(string));
    
            var keywordCodeParameter = keywordCode != null ?
                new ObjectParameter("KeywordCode", keywordCode) :
                new ObjectParameter("KeywordCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            var keywordBidParameter = keywordBid != null ?
                new ObjectParameter("KeywordBid", keywordBid) :
                new ObjectParameter("KeywordBid", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateMappedKeywords", keywordNameParameter, keywordCodeParameter, adGroupCodeParameter, keywordBidParameter, createdByParameter, flagParameter);
        }
    
        public virtual int prcCreatePhrase(string phraseName, Nullable<System.DateTime> createdOn, string createdBy, Nullable<int> traffic, string category, string inputPhraseCode, string status)
        {
            var phraseNameParameter = phraseName != null ?
                new ObjectParameter("PhraseName", phraseName) :
                new ObjectParameter("PhraseName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("CreatedOn", createdOn) :
                new ObjectParameter("CreatedOn", typeof(System.DateTime));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var trafficParameter = traffic.HasValue ?
                new ObjectParameter("Traffic", traffic) :
                new ObjectParameter("Traffic", typeof(int));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            var inputPhraseCodeParameter = inputPhraseCode != null ?
                new ObjectParameter("InputPhraseCode", inputPhraseCode) :
                new ObjectParameter("InputPhraseCode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreatePhrase", phraseNameParameter, createdOnParameter, createdByParameter, trafficParameter, categoryParameter, inputPhraseCodeParameter, statusParameter);
        }
    
        public virtual int prcCreateStudent(string firstName, string middleName, string lastName, string location, string email, string pass, string contact, string inputLocationCode, string inputStudentCode, string status)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var inputLocationCodeParameter = inputLocationCode != null ?
                new ObjectParameter("InputLocationCode", inputLocationCode) :
                new ObjectParameter("InputLocationCode", typeof(string));
    
            var inputStudentCodeParameter = inputStudentCode != null ?
                new ObjectParameter("InputStudentCode", inputStudentCode) :
                new ObjectParameter("InputStudentCode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateStudent", firstNameParameter, middleNameParameter, lastNameParameter, locationParameter, emailParameter, passParameter, contactParameter, inputLocationCodeParameter, inputStudentCodeParameter, statusParameter);
        }
    
        public virtual int prcCreateTrainer(string firstName, string middleName, string lastName, string location, string email, string pass, string contact, string inputLocationCode, string inputTrainerCode, string status)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var inputLocationCodeParameter = inputLocationCode != null ?
                new ObjectParameter("InputLocationCode", inputLocationCode) :
                new ObjectParameter("InputLocationCode", typeof(string));
    
            var inputTrainerCodeParameter = inputTrainerCode != null ?
                new ObjectParameter("InputTrainerCode", inputTrainerCode) :
                new ObjectParameter("InputTrainerCode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcCreateTrainer", firstNameParameter, middleNameParameter, lastNameParameter, locationParameter, emailParameter, passParameter, contactParameter, inputLocationCodeParameter, inputTrainerCodeParameter, statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> prcEligibleForRFA(string batchCode, string accCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("prcEligibleForRFA", batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<prcGetAccntsDetails_Result> prcGetAccntsDetails(string trainerCode, string batchCode)
        {
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetAccntsDetails_Result>("prcGetAccntsDetails", trainerCodeParameter, batchCodeParameter);
        }
    
        public virtual ObjectResult<prcGetAccountRpt_Result> prcGetAccountRpt(string batchCode, string accCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetAccountRpt_Result>("prcGetAccountRpt", batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<prcGetAccountRpt_03_Aug_16_Result> prcGetAccountRpt_03_Aug_16(string batchCode, string accCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetAccountRpt_03_Aug_16_Result>("prcGetAccountRpt_03_Aug_16", batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<prcGetAdGroupsByID_Result> prcGetAdGroupsByID(string campaignCode, string adGroupCode)
        {
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetAdGroupsByID_Result>("prcGetAdGroupsByID", campaignCodeParameter, adGroupCodeParameter);
        }
    
        public virtual ObjectResult<prcGetBatchesOnDemand_Result> prcGetBatchesOnDemand(Nullable<int> batchTime, string trainerCode, string locationCode, string batchCode)
        {
            var batchTimeParameter = batchTime.HasValue ?
                new ObjectParameter("BatchTime", batchTime) :
                new ObjectParameter("BatchTime", typeof(int));
    
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            var locationCodeParameter = locationCode != null ?
                new ObjectParameter("LocationCode", locationCode) :
                new ObjectParameter("LocationCode", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetBatchesOnDemand_Result>("prcGetBatchesOnDemand", batchTimeParameter, trainerCodeParameter, locationCodeParameter, batchCodeParameter);
        }
    
        public virtual ObjectResult<prcGetCampaign_Result> prcGetCampaign(string batchCode, string accCode, string campaignCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetCampaign_Result>("prcGetCampaign", batchCodeParameter, accCodeParameter, campaignCodeParameter);
        }
    
        public virtual ObjectResult<prcGetCampaign_03_Aug_2019_Result> prcGetCampaign_03_Aug_2019(string batchCode, string accCode, string campaignCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetCampaign_03_Aug_2019_Result>("prcGetCampaign_03_Aug_2019", batchCodeParameter, accCodeParameter, campaignCodeParameter);
        }
    
        public virtual ObjectResult<prcGetCampaign_24_07_16_Result> prcGetCampaign_24_07_16(string batchCode, string accCode, string campaignCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetCampaign_24_07_16_Result>("prcGetCampaign_24_07_16", batchCodeParameter, accCodeParameter, campaignCodeParameter);
        }
    
        public virtual ObjectResult<prcGetCampaign_old_Result> prcGetCampaign_old(string userid, string campaignCode)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetCampaign_old_Result>("prcGetCampaign_old", useridParameter, campaignCodeParameter);
        }
    
        public virtual ObjectResult<prcGetCurrentBatches_Result> prcGetCurrentBatches(string userid, string batchType, string batchCode)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var batchTypeParameter = batchType != null ?
                new ObjectParameter("BatchType", batchType) :
                new ObjectParameter("BatchType", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetCurrentBatches_Result>("prcGetCurrentBatches", useridParameter, batchTypeParameter, batchCodeParameter);
        }
    
        public virtual ObjectResult<prcGetDistAdGroups_Result> prcGetDistAdGroups(string campaignCode, string createdBy)
        {
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetDistAdGroups_Result>("prcGetDistAdGroups", campaignCodeParameter, createdByParameter);
        }
    
        public virtual ObjectResult<prcGetGraphs_Result> prcGetGraphs(string batchCode, string accCode, string rFAID)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var rFAIDParameter = rFAID != null ?
                new ObjectParameter("RFAID", rFAID) :
                new ObjectParameter("RFAID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetGraphs_Result>("prcGetGraphs", batchCodeParameter, accCodeParameter, rFAIDParameter);
        }
    
        public virtual ObjectResult<prcGetKeywords_Result> prcGetKeywords(string keywordtxt, Nullable<int> flag)
        {
            var keywordtxtParameter = keywordtxt != null ?
                new ObjectParameter("Keywordtxt", keywordtxt) :
                new ObjectParameter("Keywordtxt", typeof(string));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetKeywords_Result>("prcGetKeywords", keywordtxtParameter, flagParameter);
        }
    
        public virtual ObjectResult<prcGetRemainingAccounts_Result> prcGetRemainingAccounts(string accCode, string trainerCode, string batchCode)
        {
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetRemainingAccounts_Result>("prcGetRemainingAccounts", accCodeParameter, trainerCodeParameter, batchCodeParameter);
        }
    
        public virtual ObjectResult<prcGetRFAAccCount_Result> prcGetRFAAccCount(string trainerCode, string batchCode, string query)
        {
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetRFAAccCount_Result>("prcGetRFAAccCount", trainerCodeParameter, batchCodeParameter, queryParameter);
        }
    
        public virtual ObjectResult<prcGetRfaHistoriesByGraph_Result> prcGetRfaHistoriesByGraph(string batchCode, string accCode, string rFAID)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var rFAIDParameter = rFAID != null ?
                new ObjectParameter("RFAID", rFAID) :
                new ObjectParameter("RFAID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetRfaHistoriesByGraph_Result>("prcGetRfaHistoriesByGraph", batchCodeParameter, accCodeParameter, rFAIDParameter);
        }
    
        public virtual ObjectResult<prcGetUserDetails_Result> prcGetUserDetails(string emailID)
        {
            var emailIDParameter = emailID != null ?
                new ObjectParameter("emailID", emailID) :
                new ObjectParameter("emailID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcGetUserDetails_Result>("prcGetUserDetails", emailIDParameter);
        }
    
        public virtual ObjectResult<prcPhraseOnDemand_Result> prcPhraseOnDemand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcPhraseOnDemand_Result>("prcPhraseOnDemand");
        }
    
        public virtual int prcSaveAccount(string studentIDS, string accountID, Nullable<int> status, string trainerCode)
        {
            var studentIDSParameter = studentIDS != null ?
                new ObjectParameter("StudentIDS", studentIDS) :
                new ObjectParameter("StudentIDS", typeof(string));
    
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcSaveAccount", studentIDSParameter, accountIDParameter, statusParameter, trainerCodeParameter);
        }
    
        public virtual ObjectResult<prcSrudentsPerBatches_Result> prcSrudentsPerBatches(string batchCode, string accCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcSrudentsPerBatches_Result>("prcSrudentsPerBatches", batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<prcStudentOnDemand_Result> prcStudentOnDemand(string batchCode, string locationCode, string studentCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var locationCodeParameter = locationCode != null ?
                new ObjectParameter("LocationCode", locationCode) :
                new ObjectParameter("LocationCode", typeof(string));
    
            var studentCodeParameter = studentCode != null ?
                new ObjectParameter("StudentCode", studentCode) :
                new ObjectParameter("StudentCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcStudentOnDemand_Result>("prcStudentOnDemand", batchCodeParameter, locationCodeParameter, studentCodeParameter);
        }
    
        public virtual ObjectResult<prcTrainerOnDemand_Result> prcTrainerOnDemand(string batchCode, string locationCode, string trainerCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var locationCodeParameter = locationCode != null ?
                new ObjectParameter("LocationCode", locationCode) :
                new ObjectParameter("LocationCode", typeof(string));
    
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcTrainerOnDemand_Result>("prcTrainerOnDemand", batchCodeParameter, locationCodeParameter, trainerCodeParameter);
        }
    
        public virtual int prcUpdateAdGroup(string userid, string campaignCode, string adGroupCode, string adGroupName)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var campaignCodeParameter = campaignCode != null ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            var adGroupNameParameter = adGroupName != null ?
                new ObjectParameter("AdGroupName", adGroupName) :
                new ObjectParameter("AdGroupName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcUpdateAdGroup", useridParameter, campaignCodeParameter, adGroupCodeParameter, adGroupNameParameter);
        }
    
        public virtual int prcUpdateCampaign(string userid, Nullable<int> campaignCode, string campaignName, string location, string budget, string network, Nullable<bool> isActive)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var campaignCodeParameter = campaignCode.HasValue ?
                new ObjectParameter("CampaignCode", campaignCode) :
                new ObjectParameter("CampaignCode", typeof(int));
    
            var campaignNameParameter = campaignName != null ?
                new ObjectParameter("CampaignName", campaignName) :
                new ObjectParameter("CampaignName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var budgetParameter = budget != null ?
                new ObjectParameter("Budget", budget) :
                new ObjectParameter("Budget", typeof(string));
    
            var networkParameter = network != null ?
                new ObjectParameter("Network", network) :
                new ObjectParameter("Network", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcUpdateCampaign", useridParameter, campaignCodeParameter, campaignNameParameter, locationParameter, budgetParameter, networkParameter, isActiveParameter);
        }
    
        public virtual int prcUpdateMappedKeywords(string keywordName, string keywordCode, string adGroupCode, string keywordBid, string createdBy, Nullable<int> flag, string status)
        {
            var keywordNameParameter = keywordName != null ?
                new ObjectParameter("KeywordName", keywordName) :
                new ObjectParameter("KeywordName", typeof(string));
    
            var keywordCodeParameter = keywordCode != null ?
                new ObjectParameter("KeywordCode", keywordCode) :
                new ObjectParameter("KeywordCode", typeof(string));
    
            var adGroupCodeParameter = adGroupCode != null ?
                new ObjectParameter("AdGroupCode", adGroupCode) :
                new ObjectParameter("AdGroupCode", typeof(string));
    
            var keywordBidParameter = keywordBid != null ?
                new ObjectParameter("KeywordBid", keywordBid) :
                new ObjectParameter("KeywordBid", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcUpdateMappedKeywords", keywordNameParameter, keywordCodeParameter, adGroupCodeParameter, keywordBidParameter, createdByParameter, flagParameter, statusParameter);
        }
    
        public virtual ObjectResult<prcUserDetailsOnDemand_Result> prcUserDetailsOnDemand(Nullable<int> userType)
        {
            var userTypeParameter = userType.HasValue ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcUserDetailsOnDemand_Result>("prcUserDetailsOnDemand", userTypeParameter);
        }
    
        public virtual int RFA_Calculation(Nullable<int> batchCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation", batchCodeParameter);
        }
    
        public virtual int RFA_Calculation_01_Aug_2016()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation_01_Aug_2016");
        }
    
        public virtual int RFA_Calculation_10_10_2016()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation_10_10_2016");
        }
    
        public virtual int RFA_Calculation_18_7_16()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation_18_7_16");
        }
    
        public virtual int RFA_Calculation_22_07_16()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation_22_07_16");
        }
    
        public virtual int RFA_Calculation_23_Aug_2016()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation_23_Aug_2016");
        }
    
        public virtual int RFA_Calculation_30_Aug_2016()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation_30_Aug_2016");
        }
    
        public virtual int RFA_Calculation_bak()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFA_Calculation_bak");
        }
    
        public virtual ObjectResult<RFA_ComparisonsByAcc_Result> RFA_ComparisonsByAcc(Nullable<int> batchCode, Nullable<int> accCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            var accCodeParameter = accCode.HasValue ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RFA_ComparisonsByAcc_Result>("RFA_ComparisonsByAcc", batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<RFA_ComparisonsByRFA_Result> RFA_ComparisonsByRFA(Nullable<int> batchCode, Nullable<int> accCode)
        {
            var batchCodeParameter = batchCode.HasValue ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(int));
    
            var accCodeParameter = accCode.HasValue ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RFA_ComparisonsByRFA_Result>("RFA_ComparisonsByRFA", batchCodeParameter, accCodeParameter);
        }
    
        public virtual int RFAIniateByStudent(string accCode, string createdBy)
        {
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RFAIniateByStudent", accCodeParameter, createdByParameter);
        }
    
        public virtual int saveImportMappingKeyword(string batchCode, string accCode, Nullable<int> forceUpdate)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var forceUpdateParameter = forceUpdate.HasValue ?
                new ObjectParameter("forceUpdate", forceUpdate) :
                new ObjectParameter("forceUpdate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saveImportMappingKeyword", batchCodeParameter, accCodeParameter, forceUpdateParameter);
        }
    
        public virtual int saveImportMappingKeyword_bak(string batchCode, string accCode, Nullable<int> forceUpdate)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            var forceUpdateParameter = forceUpdate.HasValue ?
                new ObjectParameter("forceUpdate", forceUpdate) :
                new ObjectParameter("forceUpdate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saveImportMappingKeyword_bak", batchCodeParameter, accCodeParameter, forceUpdateParameter);
        }
    
        public virtual ObjectResult<sp_Get_Location_UserMaster_Result> sp_Get_Location_UserMaster(Nullable<int> userType)
        {
            var userTypeParameter = userType.HasValue ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Location_UserMaster_Result>("sp_Get_Location_UserMaster", userTypeParameter);
        }
    
        public virtual ObjectResult<sp_GetAllLocation_Result> sp_GetAllLocation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllLocation_Result>("sp_GetAllLocation");
        }
    
        public virtual int sp_resetTrainerPwd(string pwd, string userID)
        {
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_resetTrainerPwd", pwdParameter, userIDParameter);
        }
    
        public virtual int test(Nullable<int> batchTime, string trainerCode, string locationCode, string batchCode)
        {
            var batchTimeParameter = batchTime.HasValue ?
                new ObjectParameter("BatchTime", batchTime) :
                new ObjectParameter("BatchTime", typeof(int));
    
            var trainerCodeParameter = trainerCode != null ?
                new ObjectParameter("TrainerCode", trainerCode) :
                new ObjectParameter("TrainerCode", typeof(string));
    
            var locationCodeParameter = locationCode != null ?
                new ObjectParameter("LocationCode", locationCode) :
                new ObjectParameter("LocationCode", typeof(string));
    
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("test", batchTimeParameter, trainerCodeParameter, locationCodeParameter, batchCodeParameter);
        }
    
        public virtual ObjectResult<validateMappingKeword_Result> validateMappingKeword(string batchCode, string accCode)
        {
            var batchCodeParameter = batchCode != null ?
                new ObjectParameter("BatchCode", batchCode) :
                new ObjectParameter("BatchCode", typeof(string));
    
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<validateMappingKeword_Result>("validateMappingKeword", batchCodeParameter, accCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ValidateNames(string campaignName, Nullable<int> batchcode, Nullable<int> accCode)
        {
            var campaignNameParameter = campaignName != null ?
                new ObjectParameter("CampaignName", campaignName) :
                new ObjectParameter("CampaignName", typeof(string));
    
            var batchcodeParameter = batchcode.HasValue ?
                new ObjectParameter("Batchcode", batchcode) :
                new ObjectParameter("Batchcode", typeof(int));
    
            var accCodeParameter = accCode.HasValue ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValidateNames", campaignNameParameter, batchcodeParameter, accCodeParameter);
        }
    }
}
